global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: gio_gw
    scrape_interval: '1s'
    basic_auth:
       username: 'admin'
       password: 'adminadmin'
    metrics_path: '/_node/metrics/prometheus'
    static_configs:
      - targets: ['host.docker.internal:18082']
    metric_relabel_configs:
      - source_labels: [ __name__ ]
        target_label: __name__
        regex: '(.*)'
        action: replace
        replacement: gio_gw_${1}

remote_write:
  - url: "http://promscale:9201/write"

remote_read:
  - url: "http://promscale:9201/read"
    read_recent: true
